added aid for transferring
guru-desh/Intro-To-PACE-Phoenix pull request #3
Opened 2024-04-06 20:13 UTC by abishek-exe

added a line that could potentially help people from not erroring out while transferring files between devices

2024-04-07 01:12 UTC, guru-desh requested changes

2024-04-07 01:12 UTC, guru-desh commented on README.md
> +Before you use the command to transfer files, make a new instance of the terminal while your main terminal is logged into pace, and then run the rysnc/scp commands on the new terminal.
Can you explain why this is needed? Why do you need another terminal on PACE open while running the rsync/scp commands?

2024-04-07 01:12 UTC, guru-desh commented on README.md
> +Before you use the command to transfer files, make a new instance of the terminal while your main terminal is logged into pace, and then run the rysnc/scp commands on the new terminal.
Also -- you misspelled rsync as "rysnc"

2024-04-07 01:12 UTC, guru-desh commented on README.md
> +Before you use the command to transfer files, make a new instance of the terminal while your main terminal is logged into pace, and then run the rysnc/scp commands on the new terminal.
Capitalize PACE

2024-04-07 01:39 UTC, abishakex commented on README.md
> +Before you use the command to transfer files, make a new instance of the terminal while your main terminal is logged into pace, and then run the rysnc/scp commands on the new terminal.
i have no idea ngl, i just did it because chad told me to and it worked 💀

2024-04-07 02:54 UTC, guru-desh commented on README.md
> +Before you use the command to transfer files, make a new instance of the terminal while your main terminal is logged into pace, and then run the rysnc/scp commands on the new terminal.
You don't need to have another terminal. I've done rsync before without having a terminal connected to PACE.

2024-04-10 23:57 UTC, guru-desh commented
Closed based on discussion with Chad

2024-04-10 23:57 UTC, closed without merging